dist: trusty

language: python
python: '3.5'
sudo: enabled

script:
  - cd backend/codexpose/
  - pip install -r requirements.txt
  - pylint --rcfile=../../.pylintrc codexpose
  - pycodestyle codexpose/
  - pylint --rcfile=../../.pylintrc interview/
  - pycodestyle interview/

notifications:
  slack: codexpose:Lk1VuZodnuuDanuPfGBbI86y
